name: Simple Smart Contract Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"     # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. v1.0-rc1, v20.15.10-rc5

jobs:
  #  This action cleans up previously running instances of a workflow on the same branch. This accomplishes
  #  the task of automatically cancelling CI runs on pushes to the same branch, which is a common feature in
  #  most CI systems but currently not possible with GitHub actions.
  cleanup_runs:
    runs-on: ubuntu-latest
    name: Cleanup Workflows
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  build_init:
    runs-on: ubuntu-latest
    name: Build Init
    steps:
      - id: version
        run: echo "::set-output name=version::${GITHUB_REF##*/}"
    outputs:
      version: ${{ steps.version.outputs.version }}
      go_version: "1.17"

  build_smart_contract:
    runs-on: macos-latest
    needs:
      - build_init
    name: Build OSX
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install osx tools
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      - name: Build osx binary
        run: |
          make all
      - name: Sign the mac binaries with Gon
        env:
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
        run: |
          gon -log-level=info -log-json ./gon.json
      - uses: actions/upload-artifact@v2
        with:
          name: osx-zip
          path: artifacts/*.zip

  create_release:
    runs-on: ubuntu-latest
    needs:
      - build_init
      - build_smart_contract
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create release ${{ needs.build_init.outputs.version }}
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body_path: RELEASE_CHANGELOG.md
    outputs:
      release_url: ${{ steps.create_release.outputs.upload_url }}

  update_release:
    runs-on: ubuntu-latest
    needs:
      - build_init
      - create_release
    name: Attach Release Artifacts
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ needs.build_init.outputs.go_version }}
      -
        name: Download osx zip artifact
        uses: actions/download-artifact@v2
        with:
          name: osx-zip
          path: artifacts/
      -
        name: Create release items
        run: |
          make VERSION=${{ needs.build_init.outputs.version }} build-release-checksum build-release-plan build-release-proto
      -
        name: Upload osx zip artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.release_url }}
          asset_path: ./build/provenance-darwin-amd64-${{ needs.build_init.outputs.version }}.zip
          asset_name: provenance-darwin-amd64-${{ needs.build_init.outputs.version }}.zip
          asset_content_type: application/octet-stream
